-- 기존 ngl_arrears_list / ngl_receipt_list → ngl_fee_list 이관
-- 1) 미납 전체 insert (rcvmt_sn='')
-- 2) 수납은 1·2차(동일 부과키·다른 수납일련) 모두 insert
-- 3) 수납 있는 부과키의 미납 행 제거

INSERT INTO next_gen_linkage.ngl_fee_list (
  fee_status,
  rcvmt_sn,
  sgb_cd,
  lvy_key,
  dpt_nm,
  dpt_cd,
  fyr,
  act_se_cd,
  rprs_txm_cd,
  rprs_txm_nm,
  lvy_no,
  itm_sn,
  pyr_no,
  pyr_nm,
  pyr_addr,
  lvy_ymd,
  frst_pid_ymd,
  gl_nm,
  gl_mng_no,
  gl_addr,
  vtlac_bank_nm1,
  vr_actno1,
  vtlac_bank_nm2,
  vr_actno2,
  vtlac_bank_nm3,
  vr_actno3,
  vtlac_bank_nm4,
  vr_actno4,
  vtlac_bank_nm5,
  vr_actno5,
  vtlac_bank_nm6,
  vr_actno6,
  vtlac_bank_nm7,
  vr_actno7,
  vtlac_bank_nm8,
  vr_actno8,
  vtlac_bank_nm9,
  vr_actno9,
  vtlac_bank_nm10,
  vr_actno10,
  vtlac_bank_nm11,
  vr_actno11,
  vtlac_bank_nm12,
  vr_actno12,
  vtlac_bank_nm13,
  vr_actno13,
  vtlac_bank_nm14,
  vr_actno14,
  vtlac_bank_nm15,
  vr_actno15,
  vtlac_bank_nm16,
  vr_actno16,
  vtlac_bank_nm17,
  vr_actno17,
  vtlac_bank_nm18,
  vr_actno18,
  vtlac_bank_nm19,
  vr_actno19,
  vtlac_bank_nm20,
  vr_actno20,
  epay_no,
  ledger_no,
  acct_itm_cd,
  sgb_nm,
  rcvmt_se_nm,
  szr_se_nm,
  pyr_se_cd,
  pyr_mng_no,
  pyr_addr_sn,
  pyr_stt_cd,
  pyr_stt_nm,
  zip,
  lotno_road_addr_se_cd,
  pyr_cnpc_no,
  pyr_mbl_cnpc_no,
  lvy_se_cd,
  last_pid_ymd,
  pid_af_ymd,
  pid_af_amt,
  frst_pct_amt,
  lvy_stt_se_nm,
  last_pct_amt,
  last_adtn_amt,
  last_itm_intr_amt,
  itm_se_nm,
  unty_lvy_data_se_nm,
  gl_lotno_road_addr_se_cd,
  gl_zip,
  mng_item_sn1,
  mng_item_sn2,
  mng_item_sn3,
  mng_item_sn4,
  mng_item_sn5,
  mng_item_sn6,
  arr_rsn_cd,
  arr_rsn_nm,
  dft_se_nm,
  pyr_eml_addr,
  auto_pay_se_cd,
  rdt_se_nm,
  rpm_szr_vhrno,
  unty_rprs_key,
  sync_status,
  synced_at,
  created_at,
  updated_at
)
SELECT
  '미납',
  '',
  a.sgb_cd,
  a.lvy_key,
  a.dpt_nm,
  a.dpt_cd,
  a.fyr,
  a.act_se_cd,
  a.rprs_txm_cd,
  a.rprs_txm_nm,
  a.lvy_no,
  a.itm_sn,
  a.pyr_no,
  a.pyr_nm,
  a.pyr_addr,
  a.lvy_ymd,
  a.frst_pid_ymd,
  a.gl_nm,
  a.gl_mng_no,
  a.gl_addr,
  a.vtlac_bank_nm1,
  a.vr_actno1,
  a.vtlac_bank_nm2,
  a.vr_actno2,
  a.vtlac_bank_nm3,
  a.vr_actno3,
  a.vtlac_bank_nm4,
  a.vr_actno4,
  a.vtlac_bank_nm5,
  a.vr_actno5,
  a.vtlac_bank_nm6,
  a.vr_actno6,
  a.vtlac_bank_nm7,
  a.vr_actno7,
  a.vtlac_bank_nm8,
  a.vr_actno8,
  a.vtlac_bank_nm9,
  a.vr_actno9,
  a.vtlac_bank_nm10,
  a.vr_actno10,
  a.vtlac_bank_nm11,
  a.vr_actno11,
  a.vtlac_bank_nm12,
  a.vr_actno12,
  a.vtlac_bank_nm13,
  a.vr_actno13,
  a.vtlac_bank_nm14,
  a.vr_actno14,
  a.vtlac_bank_nm15,
  a.vr_actno15,
  a.vtlac_bank_nm16,
  a.vr_actno16,
  a.vtlac_bank_nm17,
  a.vr_actno17,
  a.vtlac_bank_nm18,
  a.vr_actno18,
  a.vtlac_bank_nm19,
  a.vr_actno19,
  a.vtlac_bank_nm20,
  a.vr_actno20,
  a.epay_no,
  a.ledger_no,
  a.acct_itm_cd,
  a.sgb_nm,
  a.rcvmt_se_nm,
  a.szr_se_nm,
  a.pyr_se_cd,
  a.pyr_mng_no,
  a.pyr_addr_sn,
  a.pyr_stt_cd,
  a.pyr_stt_nm,
  a.zip,
  a.lotno_road_addr_se_cd,
  a.pyr_cnpc_no,
  a.pyr_mbl_cnpc_no,
  a.lvy_se_cd,
  a.last_pid_ymd,
  a.pid_af_ymd,
  a.pid_af_amt,
  a.frst_pct_amt,
  a.lvy_stt_se_nm,
  a.last_pct_amt,
  a.last_adtn_amt,
  a.last_itm_intr_amt,
  a.itm_se_nm,
  a.unty_lvy_data_se_nm,
  a.gl_lotno_road_addr_se_cd,
  a.gl_zip,
  a.mng_item_sn1,
  a.mng_item_sn2,
  a.mng_item_sn3,
  a.mng_item_sn4,
  a.mng_item_sn5,
  a.mng_item_sn6,
  a.arr_rsn_cd,
  a.arr_rsn_nm,
  a.dft_se_nm,
  a.pyr_eml_addr,
  a.auto_pay_se_cd,
  a.rdt_se_nm,
  a.rpm_szr_vhrno,
  a.unty_rprs_key,
  a.sync_status,
  a.synced_at,
  a.created_at,
  a.updated_at
FROM next_gen_linkage.ngl_arrears_list a
WHERE a.lvy_key IS NOT NULL AND btrim(a.lvy_key) <> ''
ON CONFLICT (lvy_key, rcvmt_sn) DO NOTHING;

INSERT INTO next_gen_linkage.ngl_fee_list (
  fee_status,
  sgb_cd,
  lvy_key,
  dpt_nm,
  dpt_cd,
  fyr,
  act_se_cd,
  rprs_txm_cd,
  rprs_txm_nm,
  lvy_no,
  itm_sn,
  pyr_no,
  pyr_nm,
  pyr_addr,
  lvy_ymd,
  frst_pid_ymd,
  gl_nm,
  gl_mng_no,
  gl_addr,
  vtlac_bank_nm1,
  vr_actno1,
  vtlac_bank_nm2,
  vr_actno2,
  vtlac_bank_nm3,
  vr_actno3,
  vtlac_bank_nm4,
  vr_actno4,
  vtlac_bank_nm5,
  vr_actno5,
  vtlac_bank_nm6,
  vr_actno6,
  vtlac_bank_nm7,
  vr_actno7,
  vtlac_bank_nm8,
  vr_actno8,
  vtlac_bank_nm9,
  vr_actno9,
  vtlac_bank_nm10,
  vr_actno10,
  vtlac_bank_nm11,
  vr_actno11,
  vtlac_bank_nm12,
  vr_actno12,
  vtlac_bank_nm13,
  vr_actno13,
  vtlac_bank_nm14,
  vr_actno14,
  vtlac_bank_nm15,
  vr_actno15,
  vtlac_bank_nm16,
  vr_actno16,
  vtlac_bank_nm17,
  vr_actno17,
  vtlac_bank_nm18,
  vr_actno18,
  vtlac_bank_nm19,
  vr_actno19,
  vtlac_bank_nm20,
  vr_actno20,
  epay_no,
  ledger_no,
  acct_itm_cd,
  spac_biz_cd,
  rcvmt_sn,
  rcvmt_ymd,
  rcvmt_pct_amt,
  rcvmt_adtn_amt,
  itm_intr_amt,
  rcvmt_bank,
  rcvmt_ty_cd,
  rcvmt_ty_nm,
  act_ymd,
  pmk_ymd,
  rcvmt_se_cd,
  rcvmt_stt_se_cd,
  taxn_no,
  sync_status,
  synced_at,
  created_at,
  updated_at
)
SELECT
  '수납',
  r.sgb_cd,
  r.lvy_key,
  r.dpt_nm,
  r.dpt_cd,
  r.fyr,
  r.act_se_cd,
  r.rprs_txm_cd,
  r.rprs_txm_nm,
  r.lvy_no,
  r.itm_sn,
  r.pyr_no,
  r.pyr_nm,
  r.pyr_addr,
  r.lvy_ymd,
  r.frst_pid_ymd,
  r.gl_nm,
  r.gl_mng_no,
  r.gl_addr,
  r.vtlac_bank_nm1,
  r.vr_actno1,
  r.vtlac_bank_nm2,
  r.vr_actno2,
  r.vtlac_bank_nm3,
  r.vr_actno3,
  r.vtlac_bank_nm4,
  r.vr_actno4,
  r.vtlac_bank_nm5,
  r.vr_actno5,
  r.vtlac_bank_nm6,
  r.vr_actno6,
  r.vtlac_bank_nm7,
  r.vr_actno7,
  r.vtlac_bank_nm8,
  r.vr_actno8,
  r.vtlac_bank_nm9,
  r.vr_actno9,
  r.vtlac_bank_nm10,
  r.vr_actno10,
  r.vtlac_bank_nm11,
  r.vr_actno11,
  r.vtlac_bank_nm12,
  r.vr_actno12,
  r.vtlac_bank_nm13,
  r.vr_actno13,
  r.vtlac_bank_nm14,
  r.vr_actno14,
  r.vtlac_bank_nm15,
  r.vr_actno15,
  r.vtlac_bank_nm16,
  r.vr_actno16,
  r.vtlac_bank_nm17,
  r.vr_actno17,
  r.vtlac_bank_nm18,
  r.vr_actno18,
  r.vtlac_bank_nm19,
  r.vr_actno19,
  r.vtlac_bank_nm20,
  r.vr_actno20,
  r.epay_no,
  r.ledger_no,
  r.acct_itm_cd,
  r.spac_biz_cd,
  COALESCE(NULLIF(btrim(r.rcvmt_sn), ''), ''),
  r.rcvmt_ymd,
  r.rcvmt_pct_amt,
  r.rcvmt_adtn_amt,
  r.itm_intr_amt,
  r.rcvmt_bank,
  r.rcvmt_ty_cd,
  r.rcvmt_ty_nm,
  r.act_ymd,
  r.pmk_ymd,
  r.rcvmt_se_cd,
  r.rcvmt_stt_se_cd,
  r.taxn_no,
  r.sync_status,
  r.synced_at,
  r.created_at,
  r.updated_at
FROM next_gen_linkage.ngl_receipt_list r
WHERE r.lvy_key IS NOT NULL AND btrim(r.lvy_key) <> ''
ON CONFLICT (lvy_key, rcvmt_sn) DO UPDATE SET
  fee_status = '수납',
  sgb_cd = EXCLUDED.sgb_cd,
  dpt_nm = EXCLUDED.dpt_nm,
  dpt_cd = EXCLUDED.dpt_cd,
  fyr = EXCLUDED.fyr,
  act_se_cd = EXCLUDED.act_se_cd,
  rprs_txm_cd = EXCLUDED.rprs_txm_cd,
  rprs_txm_nm = EXCLUDED.rprs_txm_nm,
  lvy_no = EXCLUDED.lvy_no,
  itm_sn = EXCLUDED.itm_sn,
  pyr_no = EXCLUDED.pyr_no,
  pyr_nm = EXCLUDED.pyr_nm,
  pyr_addr = EXCLUDED.pyr_addr,
  lvy_ymd = EXCLUDED.lvy_ymd,
  frst_pid_ymd = EXCLUDED.frst_pid_ymd,
  gl_nm = EXCLUDED.gl_nm,
  gl_mng_no = EXCLUDED.gl_mng_no,
  gl_addr = EXCLUDED.gl_addr,
  vtlac_bank_nm1 = EXCLUDED.vtlac_bank_nm1,
  vr_actno1 = EXCLUDED.vr_actno1,
  vtlac_bank_nm2 = EXCLUDED.vtlac_bank_nm2,
  vr_actno2 = EXCLUDED.vr_actno2,
  vtlac_bank_nm3 = EXCLUDED.vtlac_bank_nm3,
  vr_actno3 = EXCLUDED.vr_actno3,
  vtlac_bank_nm4 = EXCLUDED.vtlac_bank_nm4,
  vr_actno4 = EXCLUDED.vr_actno4,
  vtlac_bank_nm5 = EXCLUDED.vtlac_bank_nm5,
  vr_actno5 = EXCLUDED.vr_actno5,
  vtlac_bank_nm6 = EXCLUDED.vtlac_bank_nm6,
  vr_actno6 = EXCLUDED.vr_actno6,
  vtlac_bank_nm7 = EXCLUDED.vtlac_bank_nm7,
  vr_actno7 = EXCLUDED.vr_actno7,
  vtlac_bank_nm8 = EXCLUDED.vtlac_bank_nm8,
  vr_actno8 = EXCLUDED.vr_actno8,
  vtlac_bank_nm9 = EXCLUDED.vtlac_bank_nm9,
  vr_actno9 = EXCLUDED.vr_actno9,
  vtlac_bank_nm10 = EXCLUDED.vtlac_bank_nm10,
  vr_actno10 = EXCLUDED.vr_actno10,
  vtlac_bank_nm11 = EXCLUDED.vtlac_bank_nm11,
  vr_actno11 = EXCLUDED.vr_actno11,
  vtlac_bank_nm12 = EXCLUDED.vtlac_bank_nm12,
  vr_actno12 = EXCLUDED.vr_actno12,
  vtlac_bank_nm13 = EXCLUDED.vtlac_bank_nm13,
  vr_actno13 = EXCLUDED.vr_actno13,
  vtlac_bank_nm14 = EXCLUDED.vtlac_bank_nm14,
  vr_actno14 = EXCLUDED.vr_actno14,
  vtlac_bank_nm15 = EXCLUDED.vtlac_bank_nm15,
  vr_actno15 = EXCLUDED.vr_actno15,
  vtlac_bank_nm16 = EXCLUDED.vtlac_bank_nm16,
  vr_actno16 = EXCLUDED.vr_actno16,
  vtlac_bank_nm17 = EXCLUDED.vtlac_bank_nm17,
  vr_actno17 = EXCLUDED.vr_actno17,
  vtlac_bank_nm18 = EXCLUDED.vtlac_bank_nm18,
  vr_actno18 = EXCLUDED.vr_actno18,
  vtlac_bank_nm19 = EXCLUDED.vtlac_bank_nm19,
  vr_actno19 = EXCLUDED.vr_actno19,
  vtlac_bank_nm20 = EXCLUDED.vtlac_bank_nm20,
  vr_actno20 = EXCLUDED.vr_actno20,
  epay_no = EXCLUDED.epay_no,
  ledger_no = EXCLUDED.ledger_no,
  acct_itm_cd = EXCLUDED.acct_itm_cd,
  spac_biz_cd = EXCLUDED.spac_biz_cd,
  rcvmt_sn = EXCLUDED.rcvmt_sn,
  rcvmt_ymd = EXCLUDED.rcvmt_ymd,
  rcvmt_pct_amt = EXCLUDED.rcvmt_pct_amt,
  rcvmt_adtn_amt = EXCLUDED.rcvmt_adtn_amt,
  itm_intr_amt = EXCLUDED.itm_intr_amt,
  rcvmt_bank = EXCLUDED.rcvmt_bank,
  rcvmt_ty_cd = EXCLUDED.rcvmt_ty_cd,
  rcvmt_ty_nm = EXCLUDED.rcvmt_ty_nm,
  act_ymd = EXCLUDED.act_ymd,
  pmk_ymd = EXCLUDED.pmk_ymd,
  rcvmt_se_cd = EXCLUDED.rcvmt_se_cd,
  rcvmt_stt_se_cd = EXCLUDED.rcvmt_stt_se_cd,
  taxn_no = EXCLUDED.taxn_no,
  sync_status = EXCLUDED.sync_status,
  synced_at = EXCLUDED.synced_at,
  updated_at = now();

-- 수납이 있는 부과키의 미납(수납일련='') 행 제거
DELETE FROM next_gen_linkage.ngl_fee_list a
WHERE a.fee_status = '미납'
  AND a.rcvmt_sn = ''
  AND EXISTS (
    SELECT 1 FROM next_gen_linkage.ngl_fee_list r
    WHERE r.lvy_key = a.lvy_key AND r.fee_status = '수납'
  );
