/**
 * Schema exports (auto-generated by scripts/update-schema-index.ts)
 */
export * from './perm';
export * from './ser';
export * from './serd';
export * from './serp_map';
export * from './sys';
export * from './sysp_map';
export * from './sysser_map';
export * from './ug';
export * from './up_map';
export * from './usr';
