/**
 * Schema exports (auto-generated by scripts/update-schema-index.ts)
 */
export * from './comp';
export * from './compd';
export * from './gp_map';
export * from './layer_detail_history';
export * from './layer_history';
export * from './perm';
export * from './ser';
export * from './serd';
export * from './serp_map';
export * from './sys';
export * from './sysp_map';
export * from './sync_log';
export * from './sysser_map';
export * from './tp_map';
export * from './ug';
export * from './up_map';
export * from './usr';
export * from './ut';
