/**
 * Schema exports (auto-generated by scripts/update-schema-index.ts)
 */
export * from './board';
export * from './comp';
export * from './compd';
export * from './excel_sync_log';
export * from './excel_upload_history';
export * from './gp_map';
export * from './integration_job_log';
export * from './layer_detail_history';
export * from './layer_history';
export * from './log_kais';
export * from './log_safetydata';
export * from './mng_version_history';
export * from './notice';
export * from './perm';
export * from './road_use_ledger';
export * from './ser';
export * from './serd';
export * from './serp_map';
export * from './sync_log';
export * from './sys';
export * from './sysp_map';
export * from './sysser_map';
export * from './tp_map';
export * from './ug';
export * from './up_map';
export * from './usr';
export * from './usr_access_request';
export * from './usr_ser_grant';
export * from './usr_sys_grant';
export * from './ut';
