import { bigint, bigserial, pgSchema, text, timestamp, unique } from 'drizzle-orm/pg-core';

/** 차세대 세외수입 — 점사용료 미납·수납 통합 */
const nextGenLinkage = pgSchema('next_gen_linkage');

export const nglFeeList = nextGenLinkage.table(
  'ngl_fee_list',
  {
    id: bigserial('id', { mode: 'number' }).primaryKey(),
    feeStatus: text('fee_status').notNull(),
    sgbCd: text('sgb_cd'),
    lvyKey: text('lvy_key'),
    dptNm: text('dpt_nm'),
    dptCd: text('dpt_cd'),
    fyr: text('fyr'),
    actSeCd: text('act_se_cd'),
    rprsTxmCd: text('rprs_txm_cd'),
    rprsTxmNm: text('rprs_txm_nm'),
    lvyNo: text('lvy_no'),
    itmSn: text('itm_sn'),
    pyrNo: text('pyr_no'),
    pyrNm: text('pyr_nm'),
    pyrAddr: text('pyr_addr'),
    lvyYmd: text('lvy_ymd'),
    frstPidYmd: text('frst_pid_ymd'),
    glNm: text('gl_nm'),
    glMngNo: text('gl_mng_no'),
    glAddr: text('gl_addr'),
    vtlacBankNm1: text('vtlac_bank_nm1'),
    vrActno1: text('vr_actno1'),
    vtlacBankNm2: text('vtlac_bank_nm2'),
    vrActno2: text('vr_actno2'),
    vtlacBankNm3: text('vtlac_bank_nm3'),
    vrActno3: text('vr_actno3'),
    vtlacBankNm4: text('vtlac_bank_nm4'),
    vrActno4: text('vr_actno4'),
    vtlacBankNm5: text('vtlac_bank_nm5'),
    vrActno5: text('vr_actno5'),
    vtlacBankNm6: text('vtlac_bank_nm6'),
    vrActno6: text('vr_actno6'),
    vtlacBankNm7: text('vtlac_bank_nm7'),
    vrActno7: text('vr_actno7'),
    vtlacBankNm8: text('vtlac_bank_nm8'),
    vrActno8: text('vr_actno8'),
    vtlacBankNm9: text('vtlac_bank_nm9'),
    vrActno9: text('vr_actno9'),
    vtlacBankNm10: text('vtlac_bank_nm10'),
    vrActno10: text('vr_actno10'),
    vtlacBankNm11: text('vtlac_bank_nm11'),
    vrActno11: text('vr_actno11'),
    vtlacBankNm12: text('vtlac_bank_nm12'),
    vrActno12: text('vr_actno12'),
    vtlacBankNm13: text('vtlac_bank_nm13'),
    vrActno13: text('vr_actno13'),
    vtlacBankNm14: text('vtlac_bank_nm14'),
    vrActno14: text('vr_actno14'),
    vtlacBankNm15: text('vtlac_bank_nm15'),
    vrActno15: text('vr_actno15'),
    vtlacBankNm16: text('vtlac_bank_nm16'),
    vrActno16: text('vr_actno16'),
    vtlacBankNm17: text('vtlac_bank_nm17'),
    vrActno17: text('vr_actno17'),
    vtlacBankNm18: text('vtlac_bank_nm18'),
    vrActno18: text('vr_actno18'),
    vtlacBankNm19: text('vtlac_bank_nm19'),
    vrActno19: text('vr_actno19'),
    vtlacBankNm20: text('vtlac_bank_nm20'),
    vrActno20: text('vr_actno20'),
    epayNo: text('epay_no'),
    ledgerNo: text('ledger_no'),
    acctItmCd: text('acct_itm_cd'),
    // 미납 전용
    sgbNm: text('sgb_nm'),
    rcvmtSeNm: text('rcvmt_se_nm'),
    szrSeNm: text('szr_se_nm'),
    pyrSeCd: text('pyr_se_cd'),
    pyrMngNo: text('pyr_mng_no'),
    pyrAddrSn: text('pyr_addr_sn'),
    pyrSttCd: text('pyr_stt_cd'),
    pyrSttNm: text('pyr_stt_nm'),
    zip: text('zip'),
    lotnoRoadAddrSeCd: text('lotno_road_addr_se_cd'),
    pyrCnpcNo: text('pyr_cnpc_no'),
    pyrMblCnpcNo: text('pyr_mbl_cnpc_no'),
    lvySeCd: text('lvy_se_cd'),
    lastPidYmd: text('last_pid_ymd'),
    pidAfYmd: text('pid_af_ymd'),
    pidAfAmt: bigint('pid_af_amt', { mode: 'number' }),
    frstPctAmt: bigint('frst_pct_amt', { mode: 'number' }),
    lvySttSeNm: text('lvy_stt_se_nm'),
    lastPctAmt: bigint('last_pct_amt', { mode: 'number' }),
    lastAdtnAmt: bigint('last_adtn_amt', { mode: 'number' }),
    lastItmIntrAmt: bigint('last_itm_intr_amt', { mode: 'number' }),
    itmSeNm: text('itm_se_nm'),
    untyLvyDataSeNm: text('unty_lvy_data_se_nm'),
    glLotnoRoadAddrSeCd: text('gl_lotno_road_addr_se_cd'),
    glZip: text('gl_zip'),
    mngItemSn1: text('mng_item_sn1'),
    mngItemSn2: text('mng_item_sn2'),
    mngItemSn3: text('mng_item_sn3'),
    mngItemSn4: text('mng_item_sn4'),
    mngItemSn5: text('mng_item_sn5'),
    mngItemSn6: text('mng_item_sn6'),
    arrRsnCd: text('arr_rsn_cd'),
    arrRsnNm: text('arr_rsn_nm'),
    dftSeNm: text('dft_se_nm'),
    pyrEmlAddr: text('pyr_eml_addr'),
    autoPaySeCd: text('auto_pay_se_cd'),
    rdtSeNm: text('rdt_se_nm'),
    rpmSzrVhrno: text('rpm_szr_vhrno'),
    untyRprsKey: text('unty_rprs_key'),
    // 수납 전용
    spacBizCd: text('spac_biz_cd'),
    rcvmtSn: text('rcvmt_sn'),
    rcvmtYmd: text('rcvmt_ymd'),
    rcvmtPctAmt: bigint('rcvmt_pct_amt', { mode: 'number' }),
    rcvmtAdtnAmt: bigint('rcvmt_adtn_amt', { mode: 'number' }),
    itmIntrAmt: bigint('itm_intr_amt', { mode: 'number' }),
    rcvmtBank: text('rcvmt_bank'),
    rcvmtTyCd: text('rcvmt_ty_cd'),
    rcvmtTyNm: text('rcvmt_ty_nm'),
    actYmd: text('act_ymd'),
    pmkYmd: text('pmk_ymd'),
    rcvmtSeCd: text('rcvmt_se_cd'),
    rcvmtSttSeCd: text('rcvmt_stt_se_cd'),
    taxnNo: text('taxn_no'),
    syncStatus: text('sync_status'),
    syncedAt: timestamp('synced_at', { withTimezone: true, mode: 'string' }),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' }),
  },
  (t) => [unique('ngl_fee_list_lvy_rcvmt_key').on(t.lvyKey, t.rcvmtSn)]
);

export const nglFeeListTableComment = '점사용료 미납·수납 통합';

export const nglFeeListColumnComments: Record<string, string> = {
  id: 'id',
  fee_status: '미납 | 수납',
  sgb_cd: '지방자치단체코드',
  lvy_key: '부과키',
  dpt_nm: '부서명',
  dpt_cd: '부서코드',
  fyr: '회계연도',
  act_se_cd: '회계구분코드',
  rprs_txm_cd: '대표세입과목코드',
  rprs_txm_nm: '대표세입과목명',
  lvy_no: '부과번호',
  itm_sn: '분납일련번호',
  pyr_no: '납부자번호',
  pyr_nm: '납부자명',
  pyr_addr: '납세자주소',
  lvy_ymd: '부과일자',
  frst_pid_ymd: '최초납기일자',
  gl_nm: '물건지명',
  gl_mng_no: '물건지관리번호',
  gl_addr: '물건지주소',
  epay_no: '전자납부번호',
  ledger_no: '대장번호',
  acct_itm_cd: '회계과목코드',
  sgb_nm: '자치단체명',
  mng_item_sn5: '관리항목5',
  mng_item_sn6: '관리항목6',
  spac_biz_cd: '특별회계사업코드',
  rcvmt_sn: '수납일련번호',
  rcvmt_ymd: '수납일자',
  sync_status: '동기화상태',
  synced_at: '동기화시각',
  created_at: '생성시각',
  updated_at: '수정시각',
};

export type NglFeeList = typeof nglFeeList.$inferSelect;
export type NewNglFeeList = typeof nglFeeList.$inferInsert;
