import { pgSchema, serial, varchar, text, boolean, timestamp, customType } from 'drizzle-orm/pg-core';

const layer = pgSchema('layer');

/** PostGIS Point EPSG:5181 */
const geomPoint5181 = customType<{ data: string | null; driverData: string | null }>({
  dataType() {
    return 'geometry(Point,5181)';
  },
});

/**
 * SOINN00001 — 지하수 개발허가(CSV 원본 컬럼 기준)
 * 스키마: layer / 원본: 20260609104414608지하수데이터_rge.csv
 * geom: 도분초 위·경도 → EPSG:4326 → EPSG:5181 Point
 */
export const soinn00001 = layer.table('SOINN00001', {
  soinnKey: serial('soinn_key').primaryKey().notNull(),
  permitReportNo: varchar('permit_report_no'),
  manageNo: varchar('manage_no'),
  facilityType: varchar('facility_type'),
  permitReportDate: varchar('permit_report_date'),
  category: varchar('category'),
  bizRegNo: varchar('biz_reg_no'),
  nameOrTrade: varchar('name_or_trade'),
  repOrTrade: varchar('rep_or_trade'),
  address: text('address'),
  phone: varchar('phone'),
  zipCode: varchar('zip_code'),
  sido: varchar('sido'),
  sigungu: varchar('sigungu'),
  eupmyeondong: varchar('eupmyeondong'),
  ri: varchar('ri'),
  san: varchar('san'),
  bunji: varchar('bunji'),
  ho: varchar('ho'),
  tong: varchar('tong'),
  ban: varchar('ban'),
  specialAddress: text('special_address'),
  specialDong: varchar('special_dong'),
  specialHo: varchar('special_ho'),
  developLocation: text('develop_location'),
  lonDeg: varchar('lon_deg'),
  lonMin: varchar('lon_min'),
  lonSec: varchar('lon_sec'),
  latDeg: varchar('lat_deg'),
  latMin: varchar('lat_min'),
  latSec: varchar('lat_sec'),
  groundwaterUse: varchar('groundwater_use'),
  useType: varchar('use_type'),
  useDetail: varchar('use_detail'),
  drinkingYn: varchar('drinking_yn'),
  permitStartDate: varchar('permit_start_date'),
  permitEndDate: varchar('permit_end_date'),
  contractorRegNo: varchar('contractor_reg_no'),
  contractorName: varchar('contractor_name'),
  contractorRep: varchar('contractor_rep'),
  contractorAddr: text('contractor_addr'),
  licenseCertNo: varchar('license_cert_no'),
  completionDate: varchar('completion_date'),
  completionCertDate: varchar('completion_cert_date'),
  elevation: varchar('elevation'),
  digDepth: varchar('dig_depth'),
  digDiameter: varchar('dig_diameter'),
  intakePlanQty: varchar('intake_plan_qty'),
  requiredQty: varchar('required_qty'),
  powerHp: varchar('power_hp'),
  dischargePipeDia: varchar('discharge_pipe_dia'),
  installDepth: varchar('install_depth'),
  pumpCapacity: varchar('pump_capacity'),
  dailyUseQty: varchar('daily_use_qty'),
  usePeriod: varchar('use_period'),
  bondPayDate: varchar('bond_pay_date'),
  bondAmount: varchar('bond_amount'),
  bondPayDetail: text('bond_pay_detail'),
  waterTestExemptYn: varchar('water_test_exempt_yn'),
  waterTestType: varchar('water_test_type'),
  waterTestDate: varchar('water_test_date'),
  waterTestResult: varchar('water_test_result'),
  endReportDate: varchar('end_report_date'),
  endReason: text('end_reason'),
  abandonDate: varchar('abandon_date'),
  abandonCause: text('abandon_cause'),
  restoreOrderDate: varchar('restore_order_date'),
  restoreDoneDate: varchar('restore_done_date'),
  abandonMethod: text('abandon_method'),
  restoreMethod: text('restore_method'),
  digRestoreMethod: text('dig_restore_method'),
  abandonHandler: varchar('abandon_handler'),
  aftercarePlanStart: varchar('aftercare_plan_start'),
  aftercarePlanEnd: varchar('aftercare_plan_end'),
  complaintWithdraw: varchar('complaint_withdraw'),
  permitCancel: varchar('permit_cancel'),
  remark: text('remark'),
  completionProcessYn: varchar('completion_process_yn'),
  /** 도분초 위·경도 → EPSG:5181 Point */
  geom: geomPoint5181('geom'),
  soinnIsDel: boolean('soinn_is_del').notNull().default(false),
  soinnCreateDate: timestamp('soinn_create_date', { mode: 'string' }),
  soinnCreateUser: varchar('soinn_create_user'),
  soinnUpdateDate: timestamp('soinn_update_date', { mode: 'string' }),
  soinnUpdateUser: varchar('soinn_update_user'),
});

export const soinn00001TableComment = '지하수 개발허가';

export const soinn00001ColumnComments: Record<string, string> = {
  "soinn_key": "지하수개발허가키",
  "permit_report_no": "허가신고번호",
  "manage_no": "관리번호",
  "facility_type": "시설구분",
  "permit_report_date": "허가신고일",
  "category": "구분",
  "biz_reg_no": "법인_사업자_생년월일",
  "name_or_trade": "상호또는성명",
  "rep_or_trade": "대표자또는상호",
  "address": "주소",
  "phone": "전화번호",
  "zip_code": "우편번호",
  "sido": "시도",
  "sigungu": "시군구",
  "eupmyeondong": "읍면동",
  "ri": "리",
  "san": "산",
  "bunji": "번지",
  "ho": "호",
  "tong": "통",
  "ban": "반",
  "special_address": "특수주소",
  "special_dong": "특수지동",
  "special_ho": "특수지호",
  "develop_location": "개발위치",
  "lon_deg": "경도도",
  "lon_min": "경도분",
  "lon_sec": "경도초",
  "lat_deg": "위도도",
  "lat_min": "위도분",
  "lat_sec": "위도초",
  "groundwater_use": "지하수용도",
  "use_type": "용도",
  "use_detail": "세부용도",
  "drinking_yn": "음용여부",
  "permit_start_date": "허가유효시작일",
  "permit_end_date": "허가유효종료일",
  "contractor_reg_no": "시공업체등록번호",
  "contractor_name": "시공업체명",
  "contractor_rep": "대표자",
  "contractor_addr": "소재지",
  "license_cert_no": "등록증번호",
  "completion_date": "준공일자",
  "completion_cert_date": "준공증발급일",
  "elevation": "표고",
  "dig_depth": "굴착깊이",
  "dig_diameter": "굴착지름",
  "intake_plan_qty": "취수계획량",
  "required_qty": "소요수량",
  "power_hp": "동력장치마력",
  "discharge_pipe_dia": "토출관직경",
  "install_depth": "설치심도",
  "pump_capacity": "양수능력",
  "daily_use_qty": "일이용량",
  "use_period": "이용기간",
  "bond_pay_date": "이행보증금납부일자",
  "bond_amount": "금액",
  "bond_pay_detail": "납부내역",
  "water_test_exempt_yn": "수질검사면제여부",
  "water_test_type": "수질검사종류",
  "water_test_date": "수질검사일자",
  "water_test_result": "수질검사결과",
  "end_report_date": "종료신고일",
  "end_reason": "종료사유",
  "abandon_date": "폐공발생일",
  "abandon_cause": "폐공발생원인",
  "restore_order_date": "원상복구명령일",
  "restore_done_date": "원상복구이행일",
  "abandon_method": "폐공처리방법",
  "restore_method": "원상복구방법",
  "dig_restore_method": "굴착원상복구방법",
  "abandon_handler": "폐공처리자",
  "aftercare_plan_start": "사후관리시행예정일",
  "aftercare_plan_end": "사후관리시행종료일",
  "complaint_withdraw": "민원취하",
  "permit_cancel": "허가취소",
  "remark": "비고",
  "completion_process_yn": "준공처리여부",
  "geom": "위치",
  "soinn_is_del": "삭제여부",
  "soinn_create_date": "등록일시",
  "soinn_create_user": "등록자",
  "soinn_update_date": "수정일시",
  "soinn_update_user": "수정자"
};

export type Soinn00001 = typeof soinn00001.$inferSelect;
export type NewSoinn00001 = typeof soinn00001.$inferInsert;
