/** 시드 전용 — 화면은 DB 목록을 쓴다 */
import type { HandbookExampleField, HandbookProcedure } from "./roadWorkHandbookData"

const NEW_WIDEN_EXAMPLES: HandbookExampleField[] = [
  { key: "new_km", label: "신설구간", unit: "km", placeholder: "예: 4", hint: "4km 이상" },
  { key: "widen_km", label: "확장구간", unit: "km", placeholder: "예: 10", hint: "10km 이상" },
]

export const HANDBOOK_PROCEDURES: HandbookProcedure[] = [
  {
    no: 1,
    name: "전략환경영향평가",
    law: "환경영향평가법 시행령 제7조 제2항·제22조 제2항 (별표2) 제2호 마목, 제28조 제2항 제2호",
    criteria: "신설 4km 이상 또는 확장 10km 이상(왕복 2차로 이상 기존도로), 합산 1 이상",
    criteriaItems: [
      "도로(고속국도 제외) 건설공사 계획으로서 환경영향평가 대상 규모 이상인 경우",
      "신설 4km 이상(도시지역은 폭 25m 이상인 도로)",
      "왕복 2차로 이상 기존 도로 확장 10km 이상",
      "신설·확장을 함께 하면 (신설 합/4km)+(확장 합/10km) ≥ 1",
      "재협의: 도시·군관리계획 증가분이 도시지역(녹지 제외) 6만㎡, 그 외 1만㎡ 이상",
    ],
    when: "도로 노선 선정시",
    org: "별도",
    examples: NEW_WIDEN_EXAMPLES,
    exampleKind: "newWiden",
    formulaHint: "(신설합/4km)+(확장합/10km) ≥ 1",
  },
  {
    no: 2,
    name: "소규모환경영향평가",
    law: "환경영향평가법 시행령 제59조·제61조 제2항 (별표4) 제1호",
    criteria: "보전관리 5,000㎡ / 생산관리 7,500㎡ / 계획관리 10,000㎡ / 농림 7,500㎡ / 자연환경보전 5,000㎡",
    criteriaItems: [
      "관리지역은 보전관리 5,000㎡, 생산관리 7,500㎡, 계획관리 10,000㎡ 이상",
      "농림지역 7,500㎡ 이상",
      "자연환경보전지역 5,000㎡ 이상",
    ],
    when: "사업 승인전",
    org: "별도",
    examples: [
      {
        key: "zone",
        label: "용도지역",
        kind: "select",
        options: [
          { value: "보전관리", label: "보전관리지역 · 5,000㎡ 이상" },
          { value: "생산관리", label: "생산관리지역 · 7,500㎡ 이상" },
          { value: "계획관리", label: "계획관리지역 · 10,000㎡ 이상" },
          { value: "농림", label: "농림지역 · 7,500㎡ 이상" },
          { value: "자연환경보전", label: "자연환경보전지역 · 5,000㎡ 이상" },
        ],
      },
      { key: "area", label: "사업면적", unit: "㎡", placeholder: "예: 5000", hint: "선택한 지역 기준 이상" },
    ],
    exampleKind: "zoneArea",
  },
  {
    no: 3,
    name: "환경영향평가",
    law: "환경영향평가법 시행령 제31조 제2항·제47조 제2항 (별표3) 제5호",
    criteria: "신설 4km 이상 또는 확장 10km 이상(왕복 2차로 이상 기존도로), 합산 1 이상",
    criteriaItems: [
      "전략환경영향평가와 같은 규모 산식",
      "신설 4km 이상 또는 왕복 2차로 이상 기존도로 확장 10km 이상",
      "병행 시 합산 1 이상",
    ],
    when: "실시계획인가전",
    org: "별도",
    examples: NEW_WIDEN_EXAMPLES,
    exampleKind: "newWiden",
    formulaHint: "(신설합/4km)+(확장합/10km) ≥ 1",
  },
  {
    no: 4,
    name: "교통영향평가",
    law: "도시교통정비 촉진법 시행령 제13조의2 제3항 (별표1) 제1호 가목 3)",
    criteria: "신설 5km 이상(인터체인지·교차부·간선도로 접속부)",
    criteriaItems: [
      "도시계획시설사업 도로로서 총길이 5km 이상인 신설노선",
      "인터체인지, 교차 부분 및 다른 간선도로와의 접속부가 있는 경우",
    ],
    when: "실시계획인가전",
    org: "별도",
    examples: [{ key: "new_km", label: "신설구간", unit: "km", placeholder: "예: 5", hint: "5km 이상" }],
    exampleKind: "newLen5",
  },
  {
    no: 5,
    name: "교통안전진단",
    law: "교통안전법 제34조, 시행령 제22조 (별표2)",
    criteria: "일반국도·고속국도 5km / 특별시·광역시·지방도 3km / 시도·군도·구도 1km",
    criteriaItems: [
      "도시계획시설사업 또는 도로법 도로 건설",
      "일반국도·고속국도 총 길이 5km 이상",
      "특별시·광역시·지방도(국가지원지방도 포함) 3km 이상",
      "시도·군도·구도 1km 이상",
    ],
    when: "실시계획인가전",
    org: "별도",
    examples: [
      {
        key: "roadType",
        label: "도로 종류",
        kind: "select",
        options: [
          { value: "국도", label: "일반국도·고속국도 · 5km 이상" },
          { value: "지방도", label: "특별시·광역시·지방도 · 3km 이상" },
          { value: "시도", label: "시도·군도·구도 · 1km 이상" },
        ],
      },
      { key: "len", label: "총연장", unit: "km", placeholder: "예: 5", hint: "선택한 도로 기준 이상" },
    ],
    exampleKind: "roadTypeLen",
  },
  {
    no: 6,
    name: "재해영향성검토/평가",
    law: "자연재해대책법 시행령 제6조 제1항 (별표1) 비고 제2호 다목",
    criteria: "평가: 5만㎡ 또는 10km 이상 · 검토: 5천㎡~5만㎡ 또는 2~10km",
    criteriaItems: [
      "재해영향평가: 면적 5만㎡ 이상 또는 길이 10km 이상",
      "재해영향성검토: 면적 5천㎡ 이상 5만㎡ 미만 또는 길이 2km 이상 10km 미만",
      "도시·군계획시설 결정은 부지면적 5천㎡ 또는 길이 2km 이상인 경우(도로는 길이 개념)",
    ],
    when: "도시관리계획결정(변경)시",
    org: "별도",
    examples: [
      { key: "area", label: "부지면적", unit: "㎡", placeholder: "예: 50000", hint: "평가 5만㎡ · 검토 5천㎡" },
      { key: "len", label: "길이", unit: "km", placeholder: "예: 10", hint: "평가 10km · 검토 2km" },
    ],
    exampleKind: "disaster",
  },
  {
    no: 7,
    name: "문화재지표조사",
    law: "매장문화재 보호 및 조사에 관한 법률 시행령 제4조",
    criteria: "토지 건설공사 사업면적 3만㎡ 이상",
    criteriaItems: [
      "토지에서 시행하는 건설공사로서 사업면적 3만㎡ 이상",
      "같은 목적으로 분할·연접 개발하면 전체 면적을 합산한다",
      "매장문화재 유존지역 등은 면적에서 제외",
    ],
    when: "—",
    org: "별도",
    examples: [{ key: "area", label: "사업면적", unit: "㎡", placeholder: "예: 30000", hint: "3만㎡ 이상" }],
    exampleKind: "area30000",
  },
  {
    no: 8,
    name: "설계VE",
    law: "건설기술 진흥법 시행령 제75조",
    criteria: "총공사비 100억원 이상 기본설계 및 실시설계",
    criteriaItems: [
      "총공사비 100억원 이상인 건설공사의 기본설계·실시설계",
      "시공 중 10% 이상 조정, 실시설계 완료 후 3년 경과 발주, 발주청이 필요하다고 인정하는 경우 등도 해당",
    ],
    when: "—",
    org: "별도",
    examples: [{ key: "cost", label: "총공사비", unit: "억원", placeholder: "예: 100", hint: "100억원 이상" }],
    exampleKind: "cost100",
  },
  {
    no: 9,
    name: "설계자문",
    law: "건설기술 진흥법 시행령 제19조",
    criteria: "계획·조사·설계 단계에서 1회 이상 기술자문위원회 자문",
    criteriaItems: [
      "계획·조사·설계 용역 수행단계에서 1회 이상 자문",
      "규모가 작거나 자문할 중요한 사항이 없으면 미시행",
      "시·군 조례에 따라 기술자문위원회 시행 여부를 참고한다",
    ],
    when: "용역 수행단계",
    org: "대가없음",
    note: "시·군 조례사항에 따라 기술자문위원회 시행 여부 참고",
  },
  {
    no: 10,
    name: "설계심의",
    law: "건설기술 진흥법 시행령 제17조, 시행규칙 제3조",
    criteria: "총공사비 100억원 이상(기술자문 받은 건 등 제외)",
    criteriaItems: [
      "지방자치단체 등이 시행하는 총공사비 100억원 이상 건설공사",
      "기술자문위원회 자문을 받은 공사와 국토교통부령으로 정하는 공사(설계용역 건설사업관리를 한 공사 등)는 제외",
    ],
    when: "—",
    org: "대가없음",
    note: "기술자문 수행 시 제외 — 판단 필요",
    examples: [{ key: "cost", label: "총공사비", unit: "억원", placeholder: "예: 100", hint: "100억원 이상" }],
    exampleKind: "cost100",
  },
  {
    no: 11,
    name: "설계안전성평가",
    law: "건설기술 진흥법 시행령 제75조의2, 제98조",
    criteria: "1·2종 시설물 건설공사(교량 계획에 따라 판단)",
    criteriaItems: [
      "안전관리계획 수립 대상의 실시설계",
      "1종·2종 시설물 건설공사, 지하 10m 이상 굴착, 폭발물 사용 공사 등",
      "교량 계획에 따라 수행 여부를 정한다",
    ],
    when: "설계 진행 중",
    org: "별도",
    note: "교량 계획에 따른 대상 결정 — 판단 필요",
  },
  {
    no: 12,
    name: "주민설명회",
    law: "건설기술 진흥법 시행령 제71조 제3항·제4항",
    criteria: "기본설계 시 주민의견 청취, 14일 이상 공람",
    criteriaItems: [
      "기본설계 때 주민 등 이해당사자 의견을 듣는다",
      "일간신문·홈페이지 등으로 공고하고 기본설계안을 14일 이상 공람한다",
      "기본설계를 생략하는 경우에는 실시설계 또는 타당성 조사 때 의견을 듣는다",
    ],
    when: "기본설계시",
    org: "과업포함",
  },
  {
    no: 13,
    name: "설계안전보건대장",
    law: "산업안전보건법 제67조, 시행령 제55조",
    criteria: "총공사금액 50억원 이상",
    criteriaItems: [
      "총공사금액 50억원 이상인 공사의 설계단계에서 설계안전보건대장을 작성한다",
      "계획단계 기본안전보건대장, 시공단계 공사안전보건대장과 이어진다",
    ],
    when: "설계단계",
    org: "과업포함",
    examples: [{ key: "cost", label: "총공사금액", unit: "억원", placeholder: "예: 50", hint: "50억원 이상" }],
    exampleKind: "cost50",
  },
  {
    no: 14,
    name: "도시관리계획 결정(변경)",
    law: "국토의 계획 및 이용에 관한 법률 제26조·제30조, 시행령 제25조",
    criteria: "시종점·중심선이 범위 안이면 심의 없이 경미한 변경 가능",
    criteriaItems: [
      "도로: 시점·종점이 바뀌지 않고 중심선이 종전 도로 범위를 벗어나지 않으면 지방도시계획위원회 심의 없이 변경할 수 있다",
      "그 외는 심의",
      "설계 진행에 따라 경미한 변경인지 심의인지를 정한다",
    ],
    when: "설계 진행 중",
    org: "대가없음",
    note: "설계 진행에 따른 판단 필요. 경미한 변경이면 실시계획인가와 병행 가능(약 3~4개월).",
  },
  {
    no: 15,
    name: "경관심의",
    law: "시·군 기본경관계획",
    criteria: "해당 시·군 기본경관계획을 참고하여 판단",
    criteriaItems: ["시·군 기본경관계획을 참고하여 대상 여부를 정한다"],
    when: "—",
    org: "대가없음",
  },
  {
    no: 16,
    name: "건설사업관리(설계감리)",
    law: "건설기술 진흥법 시행령 제57조",
    criteria: "1·2종 시설물 포함 또는 총공사비 300억원 이상",
    criteriaItems: [
      "1종·2종 시설물 건설공사(또는 포함)의 기본·실시설계용역",
      "신공법·특수공법으로 발주청이 필요하다고 인정하는 경우",
      "총공사비 300억원 이상인 기본·실시설계용역",
    ],
    when: "—",
    org: "별도",
    examples: [
      {
        key: "facility",
        label: "1·2종 시설물",
        kind: "select",
        options: [
          { value: "없음", label: "미포함" },
          { value: "포함", label: "포함" },
        ],
      },
      { key: "cost", label: "총공사비", unit: "억원", placeholder: "예: 300", hint: "300억원 이상" },
    ],
    exampleKind: "facilityOrCost",
  },
]
