/**
 * src/database/schema/index.ts 를 스키마 파일 목록으로 갱신 (prebuild용)
 */
import * as fs from 'fs';
import * as path from 'path';

const dir = path.join(process.cwd(), 'src/database/schema');
const files = fs
  .readdirSync(dir)
  .filter((f) => f.endsWith('.ts') && f !== 'index.ts')
  .sort();
const body = files.map((f) => `export * from './${f.replace(/\.ts$/, '')}';`).join('\n');
const out = `/**\n * Schema exports (auto-generated by scripts/update-schema-index.ts)\n */\n${body}\n`;
fs.writeFileSync(path.join(dir, 'index.ts'), out);
console.log('[schema:index]', files.length, 'modules');
