/**
 * 스키마 폴더의 .ts 파일을 스캔하여 src/database/schema/index.ts 를 자동 생성합니다.
 * 새 테이블 스키마 파일을 추가한 뒤 npm run schema:index 또는 npm run build 시 자동 실행됩니다.
 */
import * as fs from 'fs';
import * as path from 'path';

const SCHEMA_DIR = path.join(process.cwd(), 'src', 'database', 'schema');
const INDEX_FILE = path.join(SCHEMA_DIR, 'index.ts');

const HEADER = `/**
 * Schema exports (auto-generated by scripts/update-schema-index.ts)
 */
`;

function main(): void {
  if (!fs.existsSync(SCHEMA_DIR)) {
    console.error('Schema directory not found:', SCHEMA_DIR);
    process.exit(1);
  }

  const files = fs.readdirSync(SCHEMA_DIR);
  const tsFiles = files
    .filter((f) => f.endsWith('.ts') && f !== 'index.ts')
    .map((f) => f.replace(/\.ts$/, ''))
    .sort((a, b) => a.localeCompare(b, undefined, { sensitivity: 'base' }));

  const exports = tsFiles.map((name) => `export * from './${name}';`).join('\n');
  const content = HEADER + exports + '\n';

  fs.writeFileSync(INDEX_FILE, content, 'utf-8');
  console.log('Updated', INDEX_FILE, 'with', tsFiles.length, 'exports:', tsFiles.join(', '));
}

main();
