import type { LayerRowEditPreset } from "./types";
import { USAGE_DATA_AS_FIELD_LABELS } from "../../_mapContents/river/usageDataAs/usageDataAsFieldLabels";
import { OCCUPATION_LEDGER_FIELD_LABELS } from "../../_mapContents/occupationLedger/occupationLedgerFieldLabels";

/** 화면별 preset — 새 기능 추가 시 여기만 등록 */
export const LAYER_ROW_EDIT_PRESETS = {
  publicLand: {
    tableName: "public_land",
    schema: "layer",
    keyField: "id",
    excludeFields: ["parcel_address", "value_017", "value_018", "value_019"],
    dateFields: ["value_006", "value_007"],
    childTableName: "public_land_jijuk",
    childParentField: "parent_id",
  },
  roadUseLedger: {
    tableName: "road_use_ledger",
    schema: "layer",
    keyField: "id",
    excludeFields: ["parcel_address"],
    dateFields: ["use_permit_date", "use_start", "use_end"],
    childTableName: "road_use_ledger_jijuk",
    childParentField: "parent_id",
  },
  riverUseLedger: {
    tableName: "river_use_ledger",
    schema: "layer",
    keyField: "id",
    excludeFields: ["parcel_address", "ledger_row_key"],
    dateFields: [],
    childTableName: "river_use_ledger_jijuk",
    childParentField: "parent_id",
  },
  usageDataAs: {
    tableName: "usage_data_as",
    schema: "layer",
    keyField: "cons_code",
    /** cons_code는 defineLayer 읽기전용 — insert 시 서버 자동 채번 */
    autoGenerateKeyOnCreate: true,
    excludeFields: [
      "ogc_fid",
      "gkey_code",
      "river_code",
      "mng_cde",
      "user_name",
      /** 상세 미표시 */
      "emd_code",
      "ri_code",
      "bobn",
      "bubn",
      "ledg_gbn",
      "temp_area",
    ],
    /** show_detail=false 속성은 더보기로 표시 */
    includeHiddenDetail: true,
    dateFields: [],
    childTableName: "usage_data_as_solo",
    additionalChildTableNames: ["usage_data_as_mgj"],
    childParentField: "cons_code",
    childAddressField: "usage_loc",
    fieldLabels: USAGE_DATA_AS_FIELD_LABELS,
    requirePeriodAndGeomOnSave: true,
  },
  waterOccupationLedger: {
    tableName: "water_occupationledger",
    schema: "layer",
    keyField: "id",
    autoGenerateKeyOnCreate: true,
    excludeFields: ["ogc_fid"],
    includeHiddenDetail: true,
    dateFields: ["perm_start_date", "perm_end_date", "permit_date"],
    childTableName: "water_occupationledger_jijuk",
    additionalChildTableNames: ["water_occupationledger_mgj"],
    childParentField: "id",
    childAddressField: "occup_place",
    fieldLabels: OCCUPATION_LEDGER_FIELD_LABELS,
    requirePeriodAndGeomOnSave: true,
  },
  roadOccupationLedger: {
    tableName: "road_occupationledger",
    schema: "layer",
    keyField: "id",
    autoGenerateKeyOnCreate: true,
    excludeFields: ["ogc_fid"],
    includeHiddenDetail: true,
    dateFields: ["perm_start_date", "perm_end_date", "permit_date"],
    childTableName: "road_occupationledger_jijuk",
    additionalChildTableNames: ["road_occupationledger_mgj"],
    childParentField: "id",
    childAddressField: "occup_place",
    fieldLabels: OCCUPATION_LEDGER_FIELD_LABELS,
    requirePeriodAndGeomOnSave: true,
  },
  publicOccupationLedger: {
    tableName: "public_occupationledger",
    schema: "layer",
    keyField: "id",
    autoGenerateKeyOnCreate: true,
    excludeFields: ["ogc_fid"],
    includeHiddenDetail: true,
    dateFields: ["perm_start_date", "perm_end_date", "permit_date"],
    childTableName: "public_occupationledger_jijuk",
    additionalChildTableNames: ["public_occupationledger_mgj"],
    childParentField: "id",
    childAddressField: "occup_place",
    fieldLabels: OCCUPATION_LEDGER_FIELD_LABELS,
    requirePeriodAndGeomOnSave: true,
  },
} as const satisfies Record<string, LayerRowEditPreset>;

export type LayerRowEditPresetKey = keyof typeof LAYER_ROW_EDIT_PRESETS;
